\c recipes_dev

INSERT INTO 
recipes(name, photo, type, cuisine,  is_vegan, difficulty, ingredients, description, calories, fat, protein, carbohydrates, sugar)
VALUES
('Peanut butter & jelly sandwich','https://images.unsplash.com/photo-1557275357-072087771588?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80','Snack', 'American', TRUE, 'easy','peanut butter, jelly, bread', 'americas favorite snack',378, '18g', '12g', '46g', '18g'),
('Chorizo tacos','https://images.unsplash.com/photo-1615818449536-f26c1e1fe0f0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=5127&q=80','Lunch','Mexican', FALSE, 'moderate','Chorizo sausage link(casing removed and meat crumbled), chipole peppers, corn tortillas, chopped onions, chopped cilantro','These chorizo tacos use just 5 ingredients and taste amazing.', 360, '26g', '18g', '14g', '1.4g'),
('Lumpia ','https://images.unsplash.com/photo-1606525437679-037aca74a3e9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80','Snack', 'Filipino',  FALSE, 'moderate','vegetable oil, lumpia wrappers, ground pork, chopped onions, crushed garlic, minced carrots, chopped green onions, sliced cabbage, cilantro, salt, black pepper, garlic powder, soy sauce,','Lumpia are fried spring rolls that are found in Filipino and Indonesian cuisines', 561, '3g', '6g', '13g', '80g'),
('Apple Strawberry Banana Smoothie','https://images.unsplash.com/photo-1591223789355-064747a09077?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80', 'breakfast','N/A',  TRUE, 'easy','Almond Milk, Apple, Strawberry, Bananas, Greek Yogurt','Start your day off right with this quick and nutritious apple smoothie, ready in minutes. This breakfast smoothie has a nice combination of fruit and is slightly sweet, creamy, and satisfying.', 550, '8g', '25g', '25g', '1g'),
('Lasagna','https://plus.unsplash.com/premium_photo-1671559021019-0268c54511b8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80','dinner', 'Italian',  FALSE, 'moderate', 'Sweet Italian Sausage, Lean Ground Beef, Minced Onions, Crushed Garlic, Canned Crushed Tomatoes, Canned Tomato Sauce, Canned Tomato Paste, Water, White Sugar, Fresh Parsley, Dried Basil, Italian Season, Salt, Black Pepper, Fennel Seeds, Lasagna Noodles, Egg, Ricotta Cheese, Mozzarella Cheese, Parmesan Cheese','This lasagna recipe takes a little work, but it is so satisfying and filling that its worth it!', 602, '21g', '44g', '35g', '9g'),
('Chicken Noodle Soup', 'https://plus.unsplash.com/premium_photo-1664472752075-d5b2b3de0a88?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1520&q=80',  'Soup', 'American',  FALSE, 'Easy', 'Butter, Onion, Celery, Carrot, Can Chicken Broth, Can Vegetable Broth, Cooked Chicken, Egg Noodles, Dried Basil, Dried Oregano, Salt, Pepper','A chicken noodle soup recipe that is a very easy, very good substitute for when you dont have time to make your soup totally from scratch', 168, '6g', '10g', '24g', '4g'),
('Fried Oreos', 'https://images.unsplash.com/photo-1552417656-f5c5bbb00244?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80','Dessert','American', TRUE,'Easy', 'Oreos, Pancake mix, Water, Powdered Sugar','Deep-fried Oreos are a carnival favorite. Oreos get dipped into pancake batter and fried — yummy!', 123, '7.8g', '1.5g', '12g', '7g'),
('Roasted Potatoes','https://images.unsplash.com/photo-1631898039984-fd5f61fe8732?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80', 'Side Dish', 'N/A',  TRUE, 'Easy','Gold Potatoes(Quartered), Olive Oil, Salt, Pepper, Rosemary','Roasted potatoes at their best — plain and simple!', 180, '8.6g', '2.7g', '23g', '4g'),
('Buttermilk Pancakes','https://images.unsplash.com/photo-1554520735-0a6b8b6ce8b7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2864&q=80','Breakfast','American',  TRUE,'Moderate', 'Flour, Baking soda, Baking Powder, Salt, Sugar, Melted Butter, Eggs, Buttermillk', 'A very light and fluffy pancake recipe that requires fresh buttermilk, but it is the best I ever made!', 250, '8g', '8g', '37g', '7g'),
('Risotto','https://plus.unsplash.com/premium_photo-1661440219827-bb6d4c6cbc98?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2787&q=80','Side Dish','Italian',  FALSE, 'Challenging', 'Arborio Rice, Butter, Shallots, Garlic, White Wine, Chicken Stock, Salt, Parmesan Cheese, Parsley','This Parmesan risotto is a wonderful side dish to pair with Italian seasoned meatloaf, add some steamed green beans to round out a weeknight meal.', 249, '8g', '5g', '35g', '0g') ,
('Mint Julep','https://images.unsplash.com/photo-1501199532894-9449c0a85a77?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2848&q=80','Beverage','Mediterranean',  TRUE, 'Moderate', 'Bourbon, Simple Syrup, Mint','Whether you’re hosting a Kentucky Derby party or you’re just craving a refreshing bourbon cocktail, this mint julep recipe is sure to hit the spot.', 199, '0g', '0g', '6.6g', '6.3g'),
('Pho', 'https://images.unsplash.com/photo-1596016764780-a5fdbe817fbe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=872&q=80', 'Soup','Vietenamese', FALSE, 'Challenging','Beef Bones, Onion, Ginger, Star Anise, Cloves, Cinnamon Sticks, Black Cardamom Pods, Fennel Seeds, Coriander Seeds, Fish Sauce, Water, Dried Rice Noodles, Thinly Sliced Beef Sirloin, Fresh Cilantro, Green Onions, Thai Basil, Bean Sprouts, Lime, Palm Sugar, Salt','Vietnamese pho soup is all about the broth! Beef bones, fish sauce, star anise, and ginger simmer for at least 6 hours, creating a complex, aromatic broth that may not be quick, but it is certainly delicious.', 509, '11g', '35g', '66g', '9g'),
('Jerk Chicken', 'https://images.unsplash.com/photo-1658833621083-01fd8a4acf19?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1636&q=80','Dinner', 'Caribbean', FALSE, 'Moderate', 'Chicken, Jerk Seasoning, Garlic Powder, Onion Powder, Thyme, Green Onion, Garlic, Scotch Bonnets, Ginger, Soy Sauce, Brown Sugar, Allspice, Cinnamon, Nutmeg, Water','This well-seasoned grilled chicken with Jamaican jerk marinade has the perfect balance of heat and sweetness.', 253, '16g', '17g', '11g', '6g'),
('Baba Ganoush','https://images.unsplash.com/photo-1627308595127-d9acf19107ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80','Snack','Middle Eastern', TRUE, 'Moderate','Eggplant, Lemon Juice, Tahini, Garlic, Cumin, Smoked Paprika, Extra Virgin Olive Oil, Chopped Parsley','This dip is creamy, delicious, and tastes great on bread, naan, or with pita! ', 246, '22.8g', '3.3g', '11.9g', '5.6g'),
('Pina Colada','https://images.unsplash.com/photo-1617728273800-1e615ab03037?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80', 'Beverage','Latin America',  TRUE, 'Easy','Pineapple Juice, Cream of Coconut, Light Rum, Ice','The pina colada is a blended drink that originated in Puerto Rico. The mixture of pineapple, coconut, and rum is a taste of the tropics.', 656, '7.1g', '1.6g', '85g', '84g'),
('Chocolate Croissants','https://images.unsplash.com/photo-1597528673850-e27492b0335f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80','Dessert','French',  FALSE, 'Challenging','Warm water, active dry yeast, Sugar, Bread Flour, Salt, Butter, Egg, Sea Salt','Also known as Pain au Chocolat this french pastry may take some time but, there’s absolutely nothing on earth better than a warm chocolate croissant that was proudly handmade in your own kitchen.', 297, '16g', '5.7g', '33g', '12g');


INSERT INTO 
    reviews (recipes_id, reviewer, title, content, rating )
VALUES
('1','George','Why is there a recipe for a peanut butter sandwich','Best sandwich ', 3),
('2','Suzette', 'Worlds Blandest Tacos','There tacos were a gross muddy mess, and a waste of good chorizo', 2 ),
('2', 'Courtney', 'Love This Recipe','My go-to taco recipe, I add avocado and sour cream, yum!', 4),
('3', 'Marasol', 'Great snack for Parties', 'Not the traditional, but this recipe is delicious and easy to make', 4),
('3', 'Jon', 'Rolls Fall apart in fryer', 'Not sure if I am making this right', 1),
('5', 'Alicia', 'Best Lasagna Ever', 'I made this recipe 5 times already, my family loves it.', 5),
('6','Roger', 'Soup was too salty','added 2 extra cups of water and still way too salty', 2),
('9', 'Kyle', 'Delicious Pancakes','made this recipe this morning for my family and it was a hit', 5),
('10', 'Sergi', 'Soggy Rice', 'Followed this recipe and ended up with rice soup', 1),
('14', 'Beatrice', 'Love this dip', 'Love baba ganoush, and this recipe did not disappoint', 4),
('13','Chloe','Not Authentic', 'The had a nice Flavor but was not Authentic', 3 ),
('12','Hugo','Absolutely Worth it', 'This recipe was time consuming, but worth every second', 5);




